services:
  tasks:
    container_name: mcmsr_${SERVER_NAME}_tasks
    build:
      context: .
      dockerfile: mcmsr_tasks/Dockerfile
    command: /bin/sh -c "/mcmsr_tasks/run_tasks.sh"
    restart: unless-stopped
    volumes:
      - ${LOGS_DIR_PATH}:/mcmsr_tasks/logs
    env_file:
      - .env

  server:
    container_name: $SERVER_NAME
    stdin_open: true
    tty: true
    build:
      dockerfile: Dockerfile
      args:
        - MODPACK_URL=$MODPACK_URL
        - SERVER_START_SCRIPT=$SERVER_START_SCRIPT
    command: /bin/sh -c "/mcmsr/run_server.sh"
    restart: unless-stopped
    ports:
      - "25565:25565"
    volumes:
      - ${WORLD_DIR_PATH}:/mcmsr_server/world
      - mcmsr_server_data:/mcmsr_server
    env_file:
      - .env

volumes:
  mcmsr_server_data:
