services:
  tasks:
    container_name: ${SERVER_NAME}_tasks
    build:
      context: .
      dockerfile: yamcsr_tasks/Dockerfile
    command: /bin/sh -c "/yamcsr_tasks/run_tasks.sh"
    restart: unless-stopped
    volumes:
      - ${LOGS_DIR_PATH}:/yamcsr_tasks/logs
    env_file:
      - .env

  server:
    container_name: $SERVER_NAME
    stdin_open: true
    tty: true
    build:
      dockerfile: Dockerfile
      args:
        - SERVER_FILES_URL=$SERVER_FILES_URL
        - SERVER_START_SCRIPT=$SERVER_START_SCRIPT
    command: /bin/sh -c "/yamcsr/run_server.sh"
    restart: unless-stopped
    ports:
      - "25565:25565"
    volumes:
      - ${WORLD_DIR_PATH}:/yamcsr_server/world
      - server_data:/yamcsr_server
    env_file:
      - .env

volumes:
  server_data:
