services:
  server:
    container_name: yamcsr_server
    stdin_open: true
    tty: true
    build:
      dockerfile: Dockerfile
      args:
        - SERVER_FILES_URL=$SERVER_FILES_URL
        - SERVER_START_SCRIPT=$SERVER_START_SCRIPT
    command: /bin/sh -c "/yamcsr/run_server.sh"
    restart: unless-stopped
    ports:
      - "25565:25565" # server default port
    volumes:
      - server_data:/yamcsr_server
    env_file:
      - .env

  tasks:
    depends_on:
      - yamcsr_server
    container_name: yamcsr_tasks
    build:
      context: .
      dockerfile: yamcsr_tasks/Dockerfile
    command: /bin/sh -c "/yamcsr_tasks/run_tasks.sh"
    restart: unless-stopped
    volumes:
      - files:/yamcsr_files
      - logs:/yamcsr_logs
      - server_data:/yamcsr_server_data
    env_file:
      - .env

  bridge:
    depends_on:
      - yamcsr_server
    container_name: yamcsr_bridge
    build:
      context: .
      dockerfile: yamcsr_bridge/Dockerfile
    command: /bin/sh -c "/yamcsr_bridge/run_bridge.sh"
    restart: unless-stopped
    ports:
      -  8989:${BRIDGE_PORT}
    volumes:
      - files:/yamcsr_files
      - logs:/yamcsr_logs
      - server_data:/yamcsr_server_data
    env_file:
      - .env

volumes:
  server_data:
    driver_opts:
      type: none
      device: $SERVER_DATA_DIR_PATH
      o: bind
  logs:
    driver_opts:
      type: none
      device: $LOGS_DIR_PATH
      o: bind
  files:
    driver_opts:
      type: none
      device: $FILES_DIR_PATH
      o: bind
