services:
  mcmsr_cron:
    container_name: mcmsr_cron
    build:
      context: .
      dockerfile: cron/Dockerfile
    command: /bin/sh -c "/cron/run_cron.sh"
    restart: unless-stopped
    env_file:
      - .env

  mcmsr_server:
    container_name: $SERVER_NAME
    stdin_open: true
    tty: true
    build:
      dockerfile: Dockerfile
      args:
        - MODPACK_URL=$MODPACK_URL
        - SERVER_START_SCRIPT=$SERVER_START_SCRIPT
    command: /bin/sh -c "/mcmsr_server/${SERVER_START_SCRIPT}"
    restart: unless-stopped
    ports:
      - "25565:25565"
    volumes:
      - ${WORLD_DIR_PATH}:/mcmsr_server/world
      - mcmsr_server_data:/mcmsr_server
    env_file:
      - .env

volumes:
  mcmsr_server_data:
